### ISSUE TITLE
What if I need to change the color?

### ISSUE THREAD

**Issue by shaunmac** [strarsis/eyeglass-inline-svg#3]
I have a hamburger icon that I want to change from white to black on hover or active... how can I do this?

**Comment by strarsis** [comment]
@shaunmac:
I worked on svg modification functions for sass/eyeglass but hadn't the time finishing them yet.

However, you can easily load the SVG as string (using the underlying [eyeglass-file-text](https://www.npmjs.com/package/eyeglass-file-text) module) and 
replace the existing fill/color with a new one, then you can inline the SVG using [inline-svg](https://github.com/strarsis/eyeglass-inline-svg/blob/master/sass/index.scss#L4)).

```sass
@import 'file-text';
@import 'inline-svg';
@import 'SassyStrings';

$svg      : file-text("./assets/svg/opt/test.svg");
$svg-hover: str-replace($svg, "fill:white", "fill:black");

.svg-test {
  background: inline-svg($svg) center no-repeat;
}
.svg-test:hover {
  background-image: inline-svg($svg-hover);
}
````
Edit: Using inline-svg(...) instead inline-svg-file(...).

**Comment by strarsis** [comment]
@shaunmac: I will close this issue for now. I have you have still questions or problems you can reopen it.
