### ISSUE TITLE
Line feed character encoding problem

### ISSUE THREAD

**Issue by jrencz** [strarsis/eyeglass-inline-svg#4]
I'm trying to replace [sass-inline-svg-utf8](https://www.npmjs.com/package/sass-inline-svg-utf8) with eyeglass-inline-svg after I added eyeglass to my project and it turns out that eyeglass-inline-svg encodes line feed characters in a way that corrupts the output.

sass-inline-svg-utf8 encodes LF to `%0A` while eyeglass-inline-svg makes it `\a`

For now I was able to fix that with a string replacement of `"\\a"` => `"%0A"` but it's inconvenient to use it each time

**Comment by strarsis** [comment]
@jrencz: eyeglass-inline-svg internally uses [eyeglass-inline-urlescape](https://github.com/strarsis/eyeglass-inline-urlescape) which in turn uses [inline-urlescape](https://github.com/strarsis/inline-urlescape).

Check out the test, how should it differ - or should the test improved by adding line feed character(s)?:
Input: https://github.com/strarsis/inline-urlescape/blob/master/test/fixtures/svg-1.svg
Expected: https://github.com/strarsis/inline-urlescape/blob/master/test/fixtures/svg-1.svg.enc

**Comment by strarsis** [comment]
@jrencz: Were you able to solve this issue?

**Comment by jrencz** [comment]
Sorry to say but I don't remember the context right now. At least that's no longer a problem for me.
