### ISSUE TITLE
Feature Request: Grunt support

### ISSUE THREAD

**Issue by momendo** [strarsis/eyeglass-inline-svg#5]
Can this be made to work with Grunt as well as Gulp?

**Comment by strarsis** [comment]
Yes, you can use the grunt sass plugin and configure it to use eyeglass, see https://github.com/sass-eyeglass/eyeglass/blob/7ff7b95df84441198caf7eab40f42e41b80f6414/site-src/docs/integrations/grunt.md.

**Comment by strarsis** [comment]
@momendo: Were you able to add the paths in Grunt using the instructions in the page I linked above?
